services:
  # Tek Servis - Hem FastAPI Backend hem Streamlit Frontend
  - type: web
    name: binance-api-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: BINANCE_BASE_URL
        value: https://testnet.binancefuture.com
      - key: ALLOCATION_PCT
        value: "10"
      - key: DEFAULT_LEVERAGE
        value: "10"
      - key: PER_TRADE_PCT
        value: "5"
      - key: SYMBOLS_WHITELIST
        value: "BTCUSDT,ETHUSDT,ADAUSDT,SOLUSDT"
      - key: DRY_RUN
        value: "true"
      - key: LEVERAGE_POLICY
        value: "fixed"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ENV
        value: "production"
      - key: BACKEND_URL
        value: "http://localhost:8000"

databases:
  # SQLite database will be handled as a file in the service
  # For production, consider using PostgreSQL